version: '3'

services:
  mysql:
    image: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: passwors
      MYSQL_DATABASE: employees
      MYSQL_USER: root
      MYSQL_PASSWORD: passwors
    ports:
      - "3306:3306"
    networks:
      - my-network

  web:
    image: my-web-server
    deploy:
      replicas: 3
      # restart_policy:
      #   condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DBHOST: mysql  # Change this line
      DBUSER: root
      DBPWD: passwors
      DATABASE: employees
      DBPORT: 3306
    networks:
      - my-network

  loadbalancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - my-network

networks:
  my-network:
    external: true
